baseURL = 'https://alekssandher.github.io/reichan-site/'
languageCode = 'en-us'
title = 'Reichan Site'

theme = 'hugo-theme-reimu'

[markup.highlight]
guessSyntax = true
noClasses = false

[params]
  pjax = true